### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/dbt-snowplow-normalize#5]
Just a suggestion - can we rename this to be closer to whatever business value this model drives?

Like, is there a specific tool or a specific use case which requires split tables?

**Comment by rlh1994** [comment]
How about something like `dbt-snowplow-composable-events`? It is for use in composable CDP tools but also the data itself is just end up in a form you can compose more things with?

**Comment by alexanderdean** [comment]
Sounds cool!
